#pragma once

#ifndef HEADER_MODULE_A_USE_MODULE
#  define HEADER_MODULE_A_USE_MODULE 1
#endif // !HEADER_MODULE_A_USE_MODULE

#ifndef HEADER_MODULE_A_USE_STD_MODULE
#  define HEADER_MODULE_A_USE_STD_MODULE 0
#endif // !HEADER_MODULE_A_USE_STD_MODULE


//#include "config.hpp"

//#define USE_MODULE HEADER_MODULE_A_USE_MODULE

//#include "module_define.hpp"

//#if HEADER_MODULE_A_USE_MODULE && !HAS_CPP_MODULES
//#  pragma error "!HAS_CPP_MODULES"
//#endif // HEADER_MODULE_A_USE_MODULE && !HAS_CPP_MODULES
//
//#if HEADER_MODULE_A_USE_STD_MODULE && !HAS_STD_MODULE
//#  pragma error "!HAS_CPP_MODULES"
//#endif // HEADER_MODULE_A_USE_STD_MODULE && !HAS_STD_MODULE

//#if !HEADER_MODULE_A_USE_MODULE && !HEADER_MODULE_A_USE_STD_MODULE
//#  include <string>
//#endif
