#ifdef MODULE_EXPORT
#  undef MODULE_EXPORT
#endif // MODULE_EXPORT

#ifdef MODULE_INLINE
#  undef MODULE_INLINE
#endif // MODULE_INLINE

#ifdef MODULE_EXPORT_BEGIN
#  undef MODULE_EXPORT_BEGIN
#endif // MODULE_EXPORT_BEGIN

#ifdef MODULE_EXPORT_END
#  undef MODULE_EXPORT_END
#endif // MODULE_EXPORT_END
